const { Schema, model, models } = require("mongoose");

const statusEnum = [
  "pending_payment",
  "Processing",
  "Shipped",
  "Delivered",
  "Returned",
  "Refunded",
  "payment failed",
];
// Stripe and Paypal were removed once the bank gateway replaced them and the
// test orders placed under them were cleared. "Card" and "Manual" remain for
// the admin-created path, which takes payment outside the website.
const paidWithEnum = ["Card", "Manual", "BankOfAmerica"];
const shippingEnum = ["standard", "priority", "express"];

const OrderSchema = new Schema(
  {
    line_items: Object,
    // Clerk user id of the account that placed the order. This — not `email` —
    // is what ties an order to a person. `email` is free text from the checkout
    // form, so a logged-in customer who types a different address files the
    // order under that address and can never see it again; it is also useless
    // as evidence in a chargeback, since it only proves someone typed it.
    // Absent on orders predating this field and on admin-created Manual orders.
    userId: { type: String, index: true },
    name: String,
    // Contact address for this order's receipt. Deliberately still the form
    // value: customers legitimately send a receipt somewhere other than their
    // account address. Ownership is userId's job, not this field's.
    email: String,
    phone: String,
    city: String,
    // Two-letter US state code, needed for the bank's address check (AVS).
    state: String,
    postal: String,
    street: String,
    country: String,
    shipping: { type: String, enum: shippingEnum },
    paid: Boolean,
    status: { type: String, enum: statusEnum },
    paidWith: { type: String, enum: paidWithEnum },
    // Bank of America (Secure Acceptance). boaTransactionUuid is generated by
    // us before the customer leaves for the gateway and echoed back on the
    // merchant POST — it's what makes a replayed confirmation a no-op.
    // boaTransactionId is the bank's own reference, needed to find the
    // transaction in the Business Center when issuing a refund.
    boaTransactionUuid: String,
    boaTransactionId: String,
    // Brand and last four only. A full card number never reaches this server.
    cardBrand: String,
    cardLast4: String,
  },
  { timestamps: true }
);

// sparse: true — Manual orders have no transaction id at all,
// and a plain unique index would treat every one of those missing values as
// the same null and collide. sparse skips indexing docs where the field is
// absent, so uniqueness only applies to orders that actually have an ID.
OrderSchema.index({ boaTransactionUuid: 1 }, { unique: true, sparse: true });
OrderSchema.index({ email: 1, paid: 1 });
OrderSchema.index({ status: 1, updatedAt: -1 });
OrderSchema.index({ createdAt: 1 });

const Order = models?.Order || model("Order", OrderSchema);

module.exports = Order;
