const { Schema, model, models } = require("mongoose");

const statusEnum = [
  "pending_payment",
  // The bank answered REVIEW: a person there is checking the payment by hand.
  // Distinct from pending_payment, which means the bank never answered at all.
  // The difference matters because pending_payment orders get swept away as
  // abandoned carts after 12 hours, and a payment under review must not be.
  "under_review",
  "Processing",
  "Shipped",
  "Delivered",
  "Returned",
  "Refunded",
  "payment failed",
];
// Stripe and Paypal were removed once the bank gateway replaced them and the
// test orders placed under them were cleared. "Card" and "Manual" remain for
// the admin-created path, which takes payment outside the website.
const paidWithEnum = ["Card", "Manual", "BankOfAmerica"];
const shippingEnum = ["standard", "priority", "express"];

const OrderSchema = new Schema(
  {
    line_items: Object,
    // Clerk user id of the account that placed the order. This — not `email` —
    // is what ties an order to a person. `email` is free text from the checkout
    // form, so a logged-in customer who types a different address files the
    // order under that address and can never see it again; it is also useless
    // as evidence in a chargeback, since it only proves someone typed it.
    // Absent on orders predating this field and on admin-created Manual orders.
    userId: { type: String, index: true },
    name: String,
    // Contact address for this order's receipt. Deliberately still the form
    // value: customers legitimately send a receipt somewhere other than their
    // account address. Ownership is userId's job, not this field's.
    email: String,
    phone: String,
    city: String,
    // Two-letter US state code, needed for the bank's address check (AVS).
    state: String,
    postal: String,
    street: String,
    country: String,
    shipping: { type: String, enum: shippingEnum },
    paid: Boolean,
    status: { type: String, enum: statusEnum },
    paidWith: { type: String, enum: paidWithEnum },
    // Bank of America (Secure Acceptance). boaTransactionUuid is generated by
    // us before the customer leaves for the gateway and echoed back on the
    // merchant POST — it's what makes a replayed confirmation a no-op.
    // boaTransactionId is the bank's own reference, needed to find the
    // transaction in the Business Center when issuing a refund.
    boaTransactionUuid: String,
    boaTransactionId: String,
    // The amount actually signed and sent to the bank at checkout (dollars,
    // rounded to the cent). merchantPost compares the bank's authorised
    // figure against this rather than only ever re-summing line_items at
    // confirmation time — a live recomputation validates against whatever the
    // order happens to total right now, not against what the customer was
    // actually shown and the bank actually agreed to. Absent on orders
    // created before this field existed; those fall back to the recomputed
    // total, same as before.
    signedAmount: Number,
    // Every order today is USD — this just makes that an explicit fact on
    // the document rather than an assumption baked into every consumer of
    // totalPaid, ahead of the day it stops being universally true.
    currency: { type: String, default: "USD" },
    // What the bank actually authorised (auth_amount), set once on ACCEPT.
    // Kept distinct from signedAmount so a partial authorisation is visible
    // as a fact in the data, not just as a reason a payment was refused.
    authorizedAmount: Number,
    authorizedAt: Date,
    // Capture happens at dispatch, not at checkout — this project has no
    // automated capture step yet, so this field exists for that later work
    // and is not populated by anything today. updatedAt cannot stand in for
    // it: an order can be touched for unrelated reasons after it is captured.
    capturedAt: Date,
    // The gateway's own decision string (ACCEPT/REVIEW/DECLINE/ERROR/CANCEL),
    // kept verbatim alongside the derived `status` — Decision Manager can
    // return a REVIEW for reasons `status` alone does not distinguish.
    boaDecision: String,
    reasonCode: String,
    avsResult: String,
    cvnResult: String,
    // Brand and last four only. A full card number never reaches this server.
    cardBrand: String,
    cardLast4: String,
    // Paid, but nobody should pack it. Set when a payment under review is
    // accepted after the device has already sold to another customer — money
    // taken, nothing to ship. Deliberately a flag rather than a status value:
    // the order genuinely is paid, and rewriting status to "payment failed"
    // would hide a charge that really happened. A person has to resolve it,
    // which is why the reason is stored in words rather than a code.
    fulfilmentBlocked: { type: Boolean, default: false },
    fulfilmentBlockReason: String,
    // When the review pending window ran out and nothing had actioned it. The
    // authorisation is NOT reversed by that sweep — Secure Acceptance keys
    // cannot return money — so this marks an order still needing a manual
    // reversal in the Business Center.
    reviewAutoRejectedAt: Date,
    // Set once, by processRefund, and never after. UpCell has no refund API
    // credentials — Secure Acceptance keys can only take payments, never
    // return them — so this records what a staff member calculated and
    // approved, not a payment that actually moved. The real refund still has
    // to be typed into the Business Center by hand, by Raymond or Yasir.
    refund: {
      // The line items' totalPaid, summed, before the fee — device and
      // accessory rows only, never the tax or shipping line.
      itemsTotal: Number,
      // 15% of itemsTotal, or 0 if waived. Never applied to tax or shipping —
      // the client's confirmed rule only ever mentions "Devices" and never
      // charges a restocking fee on money that was not paid for goods.
      restockingFee: Number,
      restockingFeeWaived: Boolean,
      // Required by the controller whenever restockingFeeWaived is true, so a
      // waived fee always has a reason attached, not just a checked box.
      waiveReason: String,
      // itemsTotal minus restockingFee. What the customer is owed, and the
      // figure staff type into the Business Center.
      amount: Number,
      // productIds of the exact line items refunded. A partial refund on a
      // multi-item order needs this to say which items, not just how much.
      itemIds: [String],
      notes: String,
      approvedBy: String,
      approvedAt: Date,
    },
  },
  { timestamps: true }
);

// sparse: true — Manual orders have no transaction id at all,
// and a plain unique index would treat every one of those missing values as
// the same null and collide. sparse skips indexing docs where the field is
// absent, so uniqueness only applies to orders that actually have an ID.
OrderSchema.index({ boaTransactionUuid: 1 }, { unique: true, sparse: true });
// Same reasoning as boaTransactionUuid above: without this, the atomic claim
// in merchantPost guarantees only that one writer wins per order — nothing
// stops the same bank transaction id from ending up recorded against two
// different orders if a reference number were ever resolved wrong. sparse,
// because Manual orders and orders still pending never had a bank transaction.
OrderSchema.index({ boaTransactionId: 1 }, { unique: true, sparse: true });
OrderSchema.index({ email: 1, paid: 1 });
OrderSchema.index({ status: 1, updatedAt: -1 });
OrderSchema.index({ createdAt: 1 });

const Order = models?.Order || model("Order", OrderSchema);

module.exports = Order;
